;;; Do not edit this file!
;;; Make changes in README.org

(setq use-package-compute-statistics t)

(setq gc-cons-threshold 100000000)
(setq read-process-output-max (* 1024 1024)) ;; 1mb

(add-hook 'after-init-hook #'(lambda ()
			       ;; restore after startup
			       (setq gc-cons-threshold 800000)))

(if (fboundp 'menu-bar-mode)
    (menu-bar-mode -1))
(if (fboundp 'tool-bar-mode)
    (tool-bar-mode -1))
(if (fboundp 'scroll-bar-mode)
    (scroll-bar-mode -1))

;; (if (not custom-enabled-themes)
;;     (load-theme 'wheatgrass t))
  (if (not custom-enabled-themes)
    (load-theme 'leuven-dark t))
